# Generated by Django 5.2.8 on 2025-11-24 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="店舗名"),
                ),
            ],
            options={
                "verbose_name": "店舗",
                "verbose_name_plural": "店舗",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField(unique=True, verbose_name="部門コード")),
                ("name", models.CharField(max_length=100, verbose_name="部門名")),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (10, "10部門"),
                            (35, "35部門"),
                            (90, "90部門"),
                            (180, "180部門"),
                        ],
                        default=180,
                        verbose_name="階層レベル",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="change.category",
                        verbose_name="親部門",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品部門",
                "verbose_name_plural": "商品部門",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="SalesRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="計上年月日")),
                ("amount_sales", models.IntegerField(default=0, verbose_name="売上金額")),
                ("amount_profit", models.IntegerField(default=0, verbose_name="荒利金額")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="change.category",
                        verbose_name="部門",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="change.shop",
                        verbose_name="店舗",
                    ),
                ),
            ],
            options={
                "verbose_name": "売上データ",
                "verbose_name_plural": "売上データ",
                "ordering": ["-date", "category__code"],
                "unique_together": {("shop", "category", "date")},
            },
        ),
    ]
