# Generated by Django 5.2.8 on 2025-11-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("change", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="code",
            field=models.IntegerField(verbose_name="部門コード"),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("code", "level")},
        ),
    ]
