# Generated by Django 5.2.8 on 2025-11-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("change", "0002_alter_category_code_alter_category_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesrecord",
            name="amount_net",
            field=models.IntegerField(default=0, verbose_name="ネット金額"),
        ),
        migrations.AddField(
            model_name="salesrecord",
            name="amount_purchase",
            field=models.IntegerField(default=0, verbose_name="買取金額"),
        ),
        migrations.AddField(
            model_name="salesrecord",
            name="amount_supply",
            field=models.IntegerField(default=0, verbose_name="仕入金額"),
        ),
        migrations.AlterField(
            model_name="salesrecord",
            name="amount_profit",
            field=models.IntegerField(default=0, verbose_name="粗利金額"),
        ),
    ]
