# Generated by Django 5.2.8 on 2025-12-05 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("change", "0003_salesrecord_amount_net_salesrecord_amount_purchase_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="年")),
                ("month", models.IntegerField(blank=True, null=True, verbose_name="月")),
                ("amount_sales", models.IntegerField(default=0, verbose_name="売上金額")),
                ("amount_profit", models.IntegerField(default=0, verbose_name="粗利金額")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="change.category",
                        verbose_name="部門",
                    ),
                ),
                (
                    "target_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary_targets",
                        to="change.category",
                        verbose_name="集計対象部門",
                    ),
                ),
            ],
            options={
                "verbose_name": "売上集計サマリー",
                "verbose_name_plural": "売上集計サマリー",
                "unique_together": {("year", "month", "category", "target_category")},
            },
        ),
    ]
