# Generated by Django 5.2.8 on 2025-12-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("change", "0004_salessummary"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="salessummary",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="salessummary",
            name="category",
        ),
        migrations.RemoveField(
            model_name="salessummary",
            name="target_category",
        ),
        migrations.AddIndex(
            model_name="salesrecord",
            index=models.Index(fields=["date"], name="change_sale_date_fdc7fc_idx"),
        ),
        migrations.AddIndex(
            model_name="salesrecord",
            index=models.Index(
                fields=["shop", "-date"], name="change_sale_shop_id_33e9bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesrecord",
            index=models.Index(
                fields=["category", "-date"], name="change_sale_categor_05d7a1_idx"
            ),
        ),
        migrations.DeleteModel(
            name="SalesSummary",
        ),
    ]
